### ISSUE TITLE
RuntimeError: Class values must be non-negative.

### ISSUE THREAD

**Issue by MMMMMz** [storyandwine/GEARSage-DGraphFin#1]
Hi, thanks for your great work!
When I run the code, it prompts this error. Then I found that there are some labels with the value of -100 in the label. What should I do with these data? Also, what does the add_label_feature() function do in feat_func.py?

`Traceback (most recent call last):
  File "main.py", line 148, in <module>
    main()

  File "main.py", line 104, in main
    data = data_process(data).to(device)

  File "/home/mazhe/labPycharm/GNN/GearSage/feat_func.py", line 109, in data_process
    x = add_label_feature(x, data.y)

  File "/home/mazhe/labPycharm/GNN/GearSage/feat_func.py", line 30, in add_label_feature
    y_one_hot = F.one_hot(y).squeeze()

RuntimeError: Class values must be non-negative.
`

**Comment by storyandwine** [comment]
There is no -100 in DgraphFin data from http://dgraph.xinye.com/

**Comment by storyandwine** [comment]
Maybe the data you use is from https://ai.ppdai.com/mirror/goToMirrorDetailSix?mirrorId=28&tabindex=3.
-100 means unknown in this competition.
For running fluently, You can simply set -100 to 0 in this function.

**Comment by storyandwine** [comment]
add_label_feature makes user-type (Background User or not and Types of Background User) a feature for propagation in GNN.
